# Generated by Django 4.0 on 2022-01-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(max_length=20)),
                ('lastprice', models.IntegerField()),
                ('demandqty', models.IntegerField()),
                ('demandprice', models.IntegerField()),
                ('supplyprice', models.IntegerField()),
                ('supplyqty', models.IntegerField()),
                ('lastqty', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
            ],
        ),
    ]
