# Generated by Django 4.0 on 2022-02-16 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0002_alter_stockdata_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='dateplaced',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
