# Generated by Django 4.0 on 2022-02-07 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itrader', '0002_publicchatroom_publicroomchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='users who are connected to the chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
