# Generated by Django 4.0 on 2022-02-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0003_alter_publicchatroom_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicroomchatmessage',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='publicroomchatmessage',
            old_name='user',
            new_name='username',
        ),
    ]
