# Generated by Django 4.0 on 2022-03-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0005_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
    ]
