# Generated by Django 4.0 on 2022-02-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0005_message_rename_publicchatroom_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
