# Generated by Django 4.0 on 2022-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0007_news_link_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sentimentscore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
