# Generated by Django 4.0 on 2022-05-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0008_news_sentimentscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itrader.stockdata')),
            ],
        ),
    ]
