# Generated by Django 4.0 on 2022-05-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0009_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='security',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
