# Generated by Django 4.0 on 2022-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0010_alter_companyprofile_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(max_length=20, unique=True)),
                ('action', models.TextField()),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
