# Generated by Django 4.0 on 2022-05-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0011_corporateaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateaction',
            name='security',
            field=models.CharField(max_length=20),
        ),
    ]
