# Generated by Django 4.0 on 2022-05-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrader', '0012_alter_corporateaction_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(max_length=200),
        ),
    ]
